// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DNan1GehTNJPtcUCQc_XsBxhcOkn_0g',
    appId: '1:3313099309:web:93a421fb8599e956358ea4',
    messagingSenderId: '3313099309',
    projectId: 'campus-connect-5c00b',
    authDomain: 'campus-connect-5c00b.firebaseapp.com',
    storageBucket: 'campus-connect-5c00b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomTcKJI90TfgjuWyCXL1esOtXvOWI8vg',
    appId: '1:3313099309:android:ad6b4a928b8112dc358ea4',
    messagingSenderId: '3313099309',
    projectId: 'campus-connect-5c00b',
    storageBucket: 'campus-connect-5c00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32Fv8Kyip7BPn2O1Quj-d3oleEjGl9eI',
    appId: '1:3313099309:ios:77ef8ee93cd40f5e358ea4',
    messagingSenderId: '3313099309',
    projectId: 'campus-connect-5c00b',
    storageBucket: 'campus-connect-5c00b.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32Fv8Kyip7BPn2O1Quj-d3oleEjGl9eI',
    appId: '1:3313099309:ios:d3b076b4cec83bf2358ea4',
    messagingSenderId: '3313099309',
    projectId: 'campus-connect-5c00b',
    storageBucket: 'campus-connect-5c00b.appspot.com',
    iosBundleId: 'com.example.campusConnect.RunnerTests',
  );
}
